### ISSUE TITLE
Movie URLs are guessable

### ISSUE THREAD

**Issue by panicbit** [ArnaudLevaufre/Cinema#5]
Movie URLs are guessable, allowing circumvention of access control to some degree.
I'd suggest making files available via a random URL and sending a `Content-Disposition` header with the original filename.

**Comment by panicbit** [comment]
Here's a PoC for guessing names that uses opensubtitles.org as filename source :zany_face:: https://gist.github.com/panicbit/c1bc480f2ae8d0acd916fe19f22ad013

**Comment by ArnaudLevaufre** [comment]
Hello and thank you for your report.

I understand the issue and I would say that it makes Cinema not suitable to be exposed on a public network. The issue here is that on a production setup I expect a reverse proxy to be setup to manage the streaming of the media files, so there is no validation of the user authentication.

Your solution could work with the current expected production setup, except maybe for the Content-Disposition which I don't have any idea how I could make nginx guess the original file name to create the Content-Disposition header filename.

I think the best solution would be to implement the file streaming from django to have a complete control over who gets to see the media files, however there might be some difficulties to properly handle video seeking from the media players. This solution would be quite interesting to implement.

Unfortunately, I lack motivation to work on side projects on my free time so I can't promise to ever implement something to resolve the issue. Meanwhile I would recommend you use this project only on you local, trusted network.

Best regards
